-- Optional explicit schema for MySQL (if you want to create table manually)
CREATE TABLE IF NOT EXISTS shipments (
    id                    INT AUTO_INCREMENT PRIMARY KEY,
    date_of_shipment      DATE,
    year                  INT,
    month                 INT,
    quarter               INT,
    hsn_code              VARCHAR(32),
    hsn_description       TEXT,
    goods_description     TEXT,
    supplier_name         TEXT,
    model_name            VARCHAR(255),
    model_number          VARCHAR(255),
    capacity_spec         VARCHAR(64),
    material_type         VARCHAR(64),
    embedded_quantity     DECIMAL(18,4),
    quantity              DECIMAL(18,4),
    unit                  VARCHAR(16),
    unit_price_inr        DECIMAL(18,4),
    total_value_inr       DECIMAL(18,4),
    unit_price_usd        DECIMAL(18,4),
    total_value_usd       DECIMAL(18,4),
    duty_paid_inr         DECIMAL(18,4),
    grand_total_inr       DECIMAL(18,4),
    landed_cost_per_unit_inr DECIMAL(18,4),
    category              VARCHAR(64),
    sub_category          VARCHAR(64),
    duty_percentage       DECIMAL(18,6),
    duty_zscore           DECIMAL(18,6),
    duty_anomaly_flag     TINYINT(1)
);
